lecture 테스트 코드 작성
gsainfoteam/gistalk-be pull request #17
Opened 2024-07-13 09:04 UTC by gurwoghd

- [ ] controller unit test
- [ ] service unit test
- [ ] repository unit test
- [ ] lecture e2e test

2024-07-15 06:53 UTC, siwonpada requested changes

2024-07-15 06:53 UTC, siwonpada commented on test/lecture/lecture.repository.spec.ts
> +  describe('getAll', () => {
getAll에서 error가 나오지는 않나요?
적어도 Prisma의 에러가 나올 수 도 있을 것 같은데요.
그리고 lecture쪽의 코드를 수정해서 Prisma의 에러가 나왔을때, internalservererror를 보내는 것이 맞을 것 같아요.

2024-07-15 06:53 UTC, siwonpada commented on test/lecture/lecture.repository.spec.ts
> +  describe('getEvaluation', () => {
내용이 없는 것 같은데요?

2024-07-15 06:53 UTC, siwonpada commented on test/lecture/lecture.controller.spec.ts
> +  const mockLectureService = {
다른 곳에서는 DeepMock를 썼는데 여기에서 사용하지 않은 이유는 뭐죠?

2024-07-15 11:30 UTC, gurwoghd commented on test/lecture/lecture.repository.spec.ts
> +  describe('getAll', () => {
수정했습니다

2024-07-15 11:30 UTC, gurwoghd commented on test/lecture/lecture.controller.spec.ts
> +  const mockLectureService = {
아 처음에는 이렇게 썼다가 뒤에 modify로 올린 커밋에서 deep mock으로 바꿨습니다.

2024-07-15 11:30 UTC, gurwoghd commented on test/lecture/lecture.repository.spec.ts
> +  describe('getEvaluation', () => {
아 빼먹었네요

2024-07-16 09:51 UTC, siwonpada commented
controller파일을 테스트하기 위해서 mock service를 만들고 가짜 app을 만들어서 사용자의 request를 dto로 잘 가져올 수 있는가, 또한, guard를 사용할 수 있는가를 test할 필요가 있어보여요. user.controller.integration.spec.ts를 참고해서 test code를 만들어줄 수 있나요?

2024-07-17 07:09 UTC, siwonpada requested changes

2024-07-17 07:09 UTC, siwonpada commented on test/lecture/lecture.controller.integration.spec.ts
> +    app.useGlobalPipes(new ValidationPipe({ transform: true }));
실제 돌아갈때는 useGlobalPipe를 사용하지 않아서, 실제랑 비슷한 환경을 위해서 이것은 지우는 것이 나을 것 같아요.

2024-07-17 07:09 UTC, siwonpada commented on test/lecture/lecture.controller.integration.spec.ts
> +  describe('getAll', () => {
다른 타입의 데이터가 들어갔을 때, 400 bad request가 나오는지 확인을 할 필요가 있을 것 같아요.

2024-07-17 07:09 UTC, siwonpada commented on test/lecture/lecture.controller.integration.spec.ts
> +  describe('getAll', () => {
아래 있는 테스트들도 마찬가지.

2024-07-17 07:09 UTC, siwonpada commented on src/lecture/lecture.repository.ts
> +    try {
try catch 문이 아니라
Promise 타입의, Promise.catch()를 사용하는 것이 다른 코드랑 통일성이 있을 것 같아요.

2024-07-17 07:09 UTC, siwonpada commented on src/lecture/lecture.repository.ts
> +    try {
아래 코드들도 마찬가지.

2024-07-17 07:32 UTC, gurwoghd commented on src/lecture/lecture.repository.ts
> +    try {
넵 반영했습니다

2024-07-18 09:03 UTC, siwonpada approved these changes

2024-07-18 09:04 UTC, merged