20 hhj
gsainfoteam/gistalk-be pull request #27
Opened 2024-07-22 09:03 UTC by gurwoghd

2024-07-22 14:33 UTC, siwonpada requested changes

2024-07-22 14:33 UTC, siwonpada commented on src/health/health.controller.ts
> +          'gistalk',
gistalk이 gistalk의 ping을 검사할 필요는 없죠, 대신 gistalk이 사용하는 서비스(e.g. infoteam-idp)에 대해서 ping을 검사할 필요가 있어보이네요.

2024-07-22 14:33 UTC, siwonpada commented on src/health/health.controller.ts
> +            this.configService.getOrThrow('THRESHOLD_GB') * 1024 * 1024 * 1024,
환경변수의 이름이 THRESHOLD_GB면 무엇에 관한 환경변수인지 잘 모를 것 같아요

2024-07-23 10:04 UTC, siwonpada commented on src/health/health.controller.ts
> +            this.configService.getOrThrow('THRESHOLD_GB') * 1024 * 1024 * 1024,
적어도 DISK_THRESHOLD_GB 라는 식의 변수이름이 더 어울릴 것 같아요.

2024-07-23 11:42 UTC, gurwoghd commented on src/health/health.controller.ts
> +          'gistalk',
수정했습니답

2024-07-23 11:42 UTC, gurwoghd commented on src/health/health.controller.ts
> +            this.configService.getOrThrow('THRESHOLD_GB') * 1024 * 1024 * 1024,
넵 수정했슴다

2024-07-23 12:12 UTC, siwonpada commented on src/health/health.controller.ts
> +          this.configService.getOrThrow('SWAGGER_AUTH_URL'),
환경변수중에 IDP_URL이 있는데 이 변수를 사용한 이유가 무엇인가요?

2024-07-23 12:16 UTC, gurwoghd commented on src/health/health.controller.ts
> +          this.configService.getOrThrow('SWAGGER_AUTH_URL'),
IDP_URL과 IDP_URL + '/token' 경로로 들어갔을 때 404 error가 뜨는 문제가 있었고, SWAGGER_AUTH_URL에 들어가니 idp로 리다이렉트돼서 해당 변수를 사용했습니다.

2024-07-23 12:18 UTC, siwonpada approved these changes

2024-07-23 12:19 UTC, siwonpada commented
conflict 해결하고 merge하면될 것 같아요

2024-07-23 12:25 UTC, merged