✨ feat: 수강신청 속도 관련 db 테이블 추가
gsainfoteam/gistalk-be pull request #38
Opened 2024-08-06 09:37 UTC by controlZ

2024-08-06 09:59 UTC, siwonpada requested changes

2024-08-06 09:59 UTC, siwonpada commented on prisma/schema.prisma
> +model CourseRegistrationRate {
해당 테이블은 수업의 소진 속도만 나타내지는 않고 있기 때문에, 조금 더 일반화된 이름을 정하는 것이 좋을 것 같아요. 차라리 Lecture section의 추가 정보를 나타내는 테이블이라는 사실을 담는 것이 어떨 까요?

2024-08-06 09:59 UTC, siwonpada commented on prisma/schema.prisma
> +
해당 정보는 년도가 달라질때 마다 다른 정보를 담게되어 있어요. 따라서 pk는 lectureId, sectionId 뿐만이 아니라 year도 추가되어야 할 것 같아요.

2024-08-06 09:59 UTC, siwonpada commented on prisma/schema.prisma
> +model CourseRegistrationRate {
나중에 시간표 데이터도 정확히 해당 테이블에 넣을 것 같아서 이름이 이러면 조금 문제가 될 것 같아요.

2024-08-06 10:05 UTC, controlZ commented on prisma/schema.prisma
> +model CourseRegistrationRate {
이름 정하기가 가장 어려운 것 같은데 lectureSectionInfo 어떤가요

2024-08-06 10:06 UTC, siwonpada commented on prisma/schema.prisma
> +model CourseRegistrationRate {
좋은 것 같아요.

2024-08-06 10:19 UTC, siwonpada requested changes
혹시 add_course ... 폴더와, change_column ... 폴더, change_table... 폴더를 지운후, prisma migration reset후에 다시 migration file을 만들어서 하나의 migration 파일로 만들어 줄 수 있나요? 의미없는 migration 파일이 늘어나는 것 같아서요.

2024-08-06 12:15 UTC, controlZ commented
넵~!

2024-08-07 07:50 UTC, siwonpada approved these changes

2024-08-08 04:23 UTC, siwonpada approved these changes

2024-08-08 12:42 UTC, siwonpada approved these changes

2024-08-08 12:42 UTC, siwonpada commented on src/lecture/lecture.repository.ts
> +          if (err.code === 'P2003') throw new ForbiddenException('invalid pk');
안 고쳐도 되기는 하지만, 저 exception message를 조금 풀어서 쓰면 좋을 것 같은 느낌 (받는 사람이 보통 프엔 혹은 외부인일 수 있으니까.)

2024-08-08 12:44 UTC, siwonpada commented
근데 저렇게 데이터를 만들면 나중에 과거 분반의 데이터를 보여줄 때, 분반 번호에 따라서 보여주거나 혹은 시간표에 따라서 보여주는 옵션 이렇게 2개의 옵션을 줘야할 수도 있겠네요.

2024-08-10 06:19 UTC, merged